image: registry.gitlab.pvt/gapa/myua/dockerbase:node20

stages:
  - deploy

deploy:
  stage: deploy
  only:
    - master
  tags:
    - myua
  script:
    - echo "//${CI_SERVER_HOST}/api/v4/projects/663/packages/npm/:_authToken=${CI_JOB_TOKEN}" > .npmrc
    - echo "strict-ssl=false" >> .npmrc
    - npm config set proxy $PROXY_HOST_MSK
    - npm config set https-proxy $PROXY_HOST_MSK
    - npm config set noproxy .pvt
    - npm ci
    - npm run build
    - npm run test
    - npm publish
